<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<div class="block-title italic primary h1">DEIN WIDERRUF IST BEI UNS EINGEGANGEN!</div>

<div class="checkout-success">
            <h2><?= /* @escapeNotVerified */ __('DU ERHÄLTST IN KÜRZE EINE BESTÄTIGUNG PER E-MAIL') ?> </h2>

   <div class="pretty-heart"></div>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary button continue" href="/motive.html"><span><?= /* @escapeNotVerified */ __('Weitere Grußbotschaft erstellen') ?></span></a>
        </div>
    </div>
</div>
