<?php

/**
 * $block Lucid\Booking\Block\Adminhtml\Order\View\Ep1Data\
 *
 */

try {
    $customerData = $block->getCustomerData();
    $step1 = $block->getStep1();
    $step2 = $block->getStep2();
    $step3 = $block->getStep3();
    $step4 = $block->getStep4();

    $ep1Url = $block->getEp1Url();



    $image = isset($step4->tmpImage) ? $ep1Url . $step4->tmpImage.'.png' : '';

}
catch(\Exception $e) {
    echo('error - ' . $e);
}

?>


<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title">Bestellung</span>
    </div>
    <div class="admin__table-wrapper">

        <div class="data-col">
            <h3>Customer 7Path Info</h3>
            <?php if(isset($customerData)): ?>
                <p>First Name - <?php echo isset($customerData->first_name) ? $customerData->first_name : '' ?></p>
                <p>Last Name - <?php echo isset($customerData->last_name) ? $customerData->last_name : '' ?></p>
                <p>Gender - <?php echo isset($customerData->gender) ? $customerData->gender : '' ?></p>
                <p>Email - <?php echo isset($customerData->email) ? $customerData->email : '' ?></p>
                <p>Birth Date - <?php echo isset($customerData->birthdate) ? $customerData->birthdate : '' ?></p>
                <p>Preferred Language - <?php echo isset($customerData->preferred_language) ? $customerData->preferred_language : ''  ?></p>
            <?php else: echo 'no customer data'; endif; ?>
        </div>

        <div class="data-col" style="width:50%">
            <h3>Motiv</h3>

                <img src="<?= $image ?>" alt="item Image" />

        </div>
    </div>
</section>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"></span>
    </div>
    <div class="admin__table-wrapper" >
        <div class="data-col">
            <h3>Grußbotschaft</h3>
            <?php if (isset($step1)): ?>
                <p>Text1: <?php echo isset($step1->text) ? $step1->text : '' ?></p>
                <p>Text2: <?php echo isset($step1->text2) ? $step1->text2 : '' ?></p>
                <p>Text3: <?php echo isset($step1->text3) ? $step1->text3 : '' ?></p>
            <?php else: echo 'no step1 data'; endif; ?>
        </div>

        <div class="data-col">
            <h3>Daten</h3>
            <?php if (isset($step2)): ?>
                <p>Item price: <?php echo isset($step2->price) ? $step2->price : '' ?></p>
                <p>Reserved Date: <?php echo isset($step2->date) ? $block->formatBlockDate($step2->date) : ''  ?></p>
                <p>Website: <?php echo isset($step2->website) ? $step2->website : '' ?></p>
                <p>Subpage: <?php echo isset($step2->subpage) ? $step2->subpage : '' ?></p>
            <?php else: echo 'no step2 data'; endif; ?>
        </div>

        <div class="data-col">
            <h3>Benachrichtigung</h3>
            <?php if (isset($step3)): ?>
                <?php if ($step3->sms_phone !== ""): ?>
                    <p>sms Phone: <?php echo isset($step3->sms_phone) ? $step3->sms_phone : '' ?></p>
                    <p>sms Text: <?php echo isset($step3->sms_text) ? $step3->sms_text : ''  ?></p>

                    <?php elseif ($step3->email_to !== ""): ?>
                    <p>Email to: <?php echo isset($step3->email_to) ? $step3->email_to : '' ?></p>
                    <p>Email text: <?php echo isset($step3->sms_text) ? $step3->sms_text : ''  ?></p>
                    <?php else: echo 'Keine Benachrichtigung'; endif; ?>
            <?php else: echo 'no data found'; endif; ?>
        </div>


    </div>
</section>


<style>
    .data-col {
        width: 25%;
        float:left;
        padding: 0 1%;
        border-left:1px solid #f0f0f0;
        min-height:200px;
    }
    .data-col:first-child {
        padding-left:0;
        border-left:0;
    }
    .data-col ul{
        padding-left:30px;
    }
</style>